version: '3.1'

services:
  web:
    build: .
    image: jlwalkerlg/ingaming:dev
    volumes:
      - .:/var/www/ingaming
    environment:
      MODE: development
      DB_HOST: db
    ports:
      - 80:80
    working_dir: /var/www/ingaming
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
